FROM node:20-alpine3.21 AS install

RUN apk add --no-cache git
RUN corepack enable

WORKDIR /app
COPY apps ./apps
COPY packages ./packages
COPY package.json ./package.json
COPY .yarnrc.yml ./.yarnrc.yml
COPY yarn.lock ./yarn.lock
COPY turbo.json ./turbo.json
RUN yarn install --frozen-lockfile

CMD ["yarn", "concurrently", "\"yarn workspace @echoing/logger dev\"", "\"yarn workspace @echoing/apis dev\""]
